### ISSUE TITLE
[Webnovel Comics] Manga List Change

### ISSUE THREAD

**Issue by esih351h** [manga-download/hakuneko#3961]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Manga List change

**To Reproduce**
1. Webnovel Comics
2. All
3. All
4. Failed to update manga list for Webnovel Comics

**Screenshots**
![Screenshot (18)](https://user-images.githubusercontent.com/6265698/133092083-4563c6f3-01ca-4076-a64e-ba90e5e6eae6.png)

**HakuNeko (please complete the following information):**
Latest

**Comment by 27136773** [comment]
Already solved in #3935.
Use `nightly build` or wait for update to be merged into `6.1.7`

**Comment by amit34521** [comment]
Hi @ronny1982 the list issue is still there for get all mangas. I created a fix but it only gives English titles to me. All indonesian and other titles are missing. Can you please reopen this issue?
