### ISSUE TITLE
[MangakakalotFun] Connector not working

### ISSUE THREAD

**Issue by wintersgrasp** [manga-download/hakuneko#4874]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot acces using hakuneko but can be accessed using browser

**To Reproduce**
1. MangakakalotFun
2. all manga titles showing and working but all chapters on all manga is not showing
3. Failed to recieve content (status 403)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/110315404/182006147-83044147-aff0-4fc1-a671-8e4e17459ab9.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by Kingjon96** [comment]
I am getting the same 403 issue.

**Comment by Druzai** [comment]
This issue has been resolved in #4876 (this connector uses `MangaHub` connector)
Use nightly version or wait for fix to be merged into `6.1.7` branch

**Comment by Kingjon96** [comment]
I tried it on nightly and I am still get the same 403 error.

**Comment by Druzai** [comment]
1. Are you on revision `master@2d3b82aa` or newer on nightly?
2. Do you get the same result using VPN?
Some users experienced that their ISP changed request headers.
3. Maybe headers must refer to the mangakakalotfun's site. Although mangahub site also works for me.
Can you change contents of this connector in path `cache/mjs/connectors/MangaKakalotFun.mjs`, restart HakuNeko and test it again?
[Path to cache folder](https://hakuneko.download/docs/install/#cache)
```js
import MangaHub from './MangaHub.mjs';

/**
 *
 */
export default class MangaKakalotFun extends MangaHub {

    /**
     *
     */
    constructor() {
        super();
        super.id = 'mangakakalotfun';
        super.label = 'MangaKakalotFun';
        this.url = 'https://mangakakalot.fun';

        this.path = 'mn01';
        this.requestOptions.headers.set('x-referer', this.url);
        this.requestOptions.headers.set('x-origin', this.url);
    }
}
```

**Comment by MikeZeDev** [comment]
There are currently problems with Mangahub too and its 403 errors fyi. I opened an issue about it.

**Comment by Druzai** [comment]
The issue with loading images on MangaHub has been fixed.
Can anyone check if MangakakalotFun connector is working normally again on nightly? @Kingjon96

**Comment by MikeZeDev** [comment]
Invalid API key or expired for MangakakalotFun when trying to update manga list. Same for Mangahub when loading a manga.

https://github.com/manga-download/hakuneko/issues/4896

**Comment by Kingjon96** [comment]
I used it last night EST and it worked on nightly.
