### ISSUE TITLE
[Download as PDF] Maximum Call stack exceeded.

### ISSUE THREAD

**Issue by Holydragoness** [manga-download/hakuneko#5450]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector:https://bato.to/
2. Name of manga: The Villainess Turns the Hourglass  (https://bato.to/series/78871/the-villainess-turns-the-hourglass) 
3. Name of chapter 17-10
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Maximum Call stack exceeded. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/71577019/216600427-028e161e-0f6e-4e8c-85e8-159d3e329921.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7@554b0c

**Comment by MikeZeDev** [comment]
Did you try NOT saving as pdf? Does this work? 
There was a recent workaround for pdf , try nightly maybe

**Comment by Holydragoness** [comment]
I tried again the same result 
![image](https://user-images.githubusercontent.com/71577019/216868521-2d644882-8b26-445b-9360-4e48999e266d.png)

And yes  I am using the nightly version. 
![image](https://user-images.githubusercontent.com/71577019/216869408-9d19ac9b-374e-4c54-9d75-de63767e6b45.png)
![image](https://user-images.githubusercontent.com/71577019/216869814-a5707c20-9697-4dd0-a7de-ae5cc20e8218.png)

The build version for nighly has a person listed and not a build version.  rev. master@811106. 

Thanks for the assistance

**Comment by MikeZeDev** [comment]
Ok, there is a problem making PDF. Thanks for the bug reporting. For now you should download normally as pictures and use external tool to make pdfs.
Idk why its happenning tbh.

**Comment by MikeZeDev** [comment]
PDf are created but invalid 
![image](https://user-images.githubusercontent.com/10671518/216934105-28eac94a-026e-4207-9f44-67ea4b80336c.png)

**Comment by MikeZeDev** [comment]
Error comes from the png module of PDFKIT. Upgrading pdfkit needed? I tried but ran into npm errors.

Since it only happend when we add a PNG to the PDF, as a workaround we could force JPEG conversion if page format is not JPEG.

```

    /**
     * Helper function to get the image type for jsPDF of the given mime type.
     * If the mime is not a spported PDF image format undefined will be returned.
     */
    _pdfImageType(image) {
        if (image.type === 'image/jpeg') {
            return 'JPEG';
        }
        //if (image.type === 'image/png') {
          //  return 'PNG';
       // }
        return undefined;
    }

```

**Comment by Holydragoness** [comment]
Should I assume that the issue has been fixed? also which version should I use, the nightly version or the stable version?

**Comment by MikeZeDev** [comment]
Its not fixed until PR is merged. The solution is not ideal i may have find another solution.
And even then, stable wont get the fix before a while so you will have to use nightly.

**Comment by Holydragoness** [comment]
How do I implement the work around? I'm very confused
